/**
 * Create SdI Invoice (XML)
 *
 * Generates an Italian e-invoice in FatturaPA format and submits it
 * to the Sistema di Interscambio via the POP API `create-xml` endpoint.
 *
 * Features:
 * - "Invio Fattura" toggle: when Yes, includes the SdI integration object
 *   ({ use: 'sdi-via-pop', action: 'create' }) so the invoice is submitted
 * - Four input modes: passthrough, form, JSON, and raw
 * - Form mode uses the shared invoice form fields (invoiceFields.ts) and
 *   the payload builder (invoicePayloadBuilder.ts) to assemble the request
 *
 * POP API endpoint: POST /create-xml
 */
import type { IExecuteFunctions, INodePropertyOptions } from 'n8n-workflow';
import { InvoicesProperties } from '../types/pop';
import { popRequest, type PopRequestOptions } from '../utils/request';
import { makeInvoiceFormFields } from './invoiceFields';
import { buildInvoicePayload, type InvoiceFormParams } from './invoicePayloadBuilder';

/** Operation metadata shown in the n8n operation selector dropdown */
export const options: INodePropertyOptions = {
	name: 'Create SdI Invoice (XML)',
	value: 'createSdiInvoiceXml',
	description:
		'Create an Italian e-invoice (FatturaPA) and/or submit to SdI, according to your POP API configuration',
	action: 'Create an SDI Invoice',
};

const OPERATION = 'createSdiInvoiceXml';

/**
 * Node properties (UI fields) for this operation.
 * Displayed when the user selects resource=invoices and operation=createSdiInvoiceXml.
 */
export const properties: InvoicesProperties = [
	// Base URL — overrides the default staging environment when filled in
	{
		displayName: 'Base URL',
		name: 'baseUrl',
		type: 'string',
		default: 'https://staging7.popapi.io/wp-json/api/v2/',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description: 'Base URL of the POP API. Change only if your environment differs from the default.',
	},
	// Configurable endpoint path — allows overriding the default route
	{
		displayName: 'Endpoint Path',
		name: 'path',
		type: 'string',
		default: 'create-xml',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description: 'Relative path of the POP endpoint. Adjust if your API uses a different route.',
	},
	// Invio Fattura toggle — controls whether the integration object is included
	{
		displayName: 'Invio Fattura',
		name: 'invioFattura',
		type: 'options',
		options: [
			{ name: 'Yes', value: 'yes' },
			{ name: 'No', value: 'no' },
		],
		default: 'no',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description:
			'Whether to include the SdI integration object in the payload to submit the invoice via POP',
	},
	// Input mode selector — determines how the request body is built
	{
		displayName: 'Input Mode',
		name: 'inputMode',
		type: 'options',
		options: [
			{ name: 'Use Incoming JSON', value: 'passthrough' },
			{ name: 'Form Fields', value: 'form' },
			{ name: 'JSON', value: 'json' },
			{ name: 'Raw (XML/Other)', value: 'raw' },
		],
		default: 'passthrough',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description: 'Use Incoming JSON forwards the input item as-is (ideal for webhooks). Form Fields lets you fill in each field. JSON and Raw allow manual payloads.',
	},
	// ── Form fields (visible when inputMode = form) ──
	// Generated by the shared factory to ensure consistency with the Peppol operation
	...makeInvoiceFormFields(OPERATION),
	// ── JSON body (visible when inputMode = json) ──
	{
		displayName: 'JSON Body',
		name: 'jsonBody',
		type: 'json',
		default:
			'{\n  "license_key": "your_license_key",\n  "data": {\n    "id": 0,\n    "filename": "",\n    "type": "invoice",\n    "version": "FPR12",\n    "customer_type": "private",\n    "transmitter_data": {},\n    "transfer_lender": {},\n    "transferee_client": {},\n    "invoice_body": {},\n    "order_items": [],\n    "payment_data": {}\n  },\n  "integration": {\n    "use": "sdi-via-pop",\n    "action": "create"\n  }\n}',
		displayOptions: {
			show: { resource: ['invoices'], operation: [OPERATION], inputMode: ['json'] },
		},
		description:
			'Complete request body as JSON. Must follow the POP API v2 create-xml schema.',
	},
	// ── Raw body (visible when inputMode = raw) ──
	{
		displayName: 'Raw Body',
		name: 'rawBody',
		type: 'string',
		default: '',
		typeOptions: { rows: 8 },
		displayOptions: {
			show: { resource: ['invoices'], operation: [OPERATION], inputMode: ['raw'] },
		},
		description: 'Raw request payload (e.g., XML) if the endpoint expects it',
	},
	// Extra headers — merged with the default headers for all input modes
	{
		displayName: 'Extra Headers (JSON)',
		name: 'headers',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description:
			'Optional additional headers as JSON object. Example: {"Content-Type":"application/xml"}.',
	},
];

/**
 * Operation handler — builds and sends the create-xml request.
 *
 * Depending on the selected input mode:
 * - passthrough: forwards the incoming n8n item JSON directly
 * - form: assembles the payload using buildInvoicePayload() with variant='sdi'
 * - json: uses the user-provided JSON body as-is
 * - raw: sends a raw string body (e.g. XML) with appropriate Content-Type
 *
 * When invioFattura='yes', the integration object is injected into the payload
 * for passthrough and json modes, or passed to the builder for form mode.
 */
export async function handler(
	this: IExecuteFunctions,
	params: {
		baseUrl?: string;
		path: string;
		invioFattura: 'yes' | 'no';
		inputMode: 'form' | 'json' | 'raw' | 'passthrough';
		jsonBody?: object;
		rawBody?: string;
		headers?: Record<string, string>;
		_itemIndex?: number;
	} & Partial<InvoiceFormParams>,
): Promise<unknown> {
	const { baseUrl, path, inputMode, invioFattura, headers } = params;
	const sendInvoice = invioFattura === 'yes';

	const requestOptions: PopRequestOptions = {
		url: path,
		method: 'POST',
		headers: {
			...(headers ?? {}),
		},
	};

	if (inputMode === 'passthrough') {
		// Forward the incoming item's JSON data directly to the API
		requestOptions.json = true;
		const itemIndex = params._itemIndex ?? 0;
		const body = { ...this.getInputData()[itemIndex].json };
		if (sendInvoice) {
			body.integration = { use: 'sdi-via-pop', action: 'create' };
		}
		requestOptions.body = body;
	} else if (inputMode === 'form') {
		// Build the structured payload from form field values
		requestOptions.json = true;
		requestOptions.body = buildInvoicePayload(params as InvoiceFormParams, 'sdi', sendInvoice);
	} else if (inputMode === 'json') {
		// Use the manually provided JSON body
		requestOptions.json = true;
		const body = (params.jsonBody ?? {}) as Record<string, unknown>;
		if (sendInvoice) {
			body.integration = { use: 'sdi-via-pop', action: 'create' };
		}
		requestOptions.body = body;
	} else {
		// Raw mode: send the body as a plain string (e.g. XML)
		requestOptions.json = false;
		requestOptions.body = params.rawBody ?? '';
		requestOptions.headers = {
			'Content-Type': requestOptions.headers?.['Content-Type'] ?? 'application/xml',
			...(requestOptions.headers ?? {}),
		};
	}

	return await popRequest.call(this, requestOptions, baseUrl);
}
