/**
 * Verify SdI Document (XML)
 *
 * Validates an XML generated by the SdI create-xml step via the POP API
 * `sdi-via-pop/document-verify` endpoint.
 *
 * Always operates in passthrough mode: the XML string is taken from the
 * incoming item (output of "Create SdI Invoice (XML)"), base64-encoded,
 * and placed in integration.xml. The license_key is auto-detected from
 * the upstream node's parameters.
 *
 * POP API endpoint: POST /sdi-via-pop/document-verify
 */
import type { IExecuteFunctions, INodePropertyOptions } from 'n8n-workflow';
import { InvoicesProperties } from '../types/pop';

// Node.js runtime provides Buffer globally; declare minimal types since
// @types/node is not installed and the tsconfig lib list omits DOM.
declare const Buffer: {
	from(data: string, encoding?: string): { toString(encoding: string): string };
};
import { popRequest, type PopRequestOptions } from '../utils/request';

/** Operation metadata shown in the n8n operation selector dropdown */
export const options: INodePropertyOptions = {
	name: 'Verify SdI Document (XML)',
	value: 'verifySdiDocument',
	description: 'Validate an SdI XML document via the POP API document-verify endpoint',
	action: 'Verify an SDI document',
};

const OPERATION = 'verifySdiDocument';

export const properties: InvoicesProperties = [
	{
		displayName: 'Environment',
		name: 'baseUrl',
		type: 'options',
		options: [
			{ name: 'Staging', value: 'staging' },
			{ name: 'Production', value: 'production' },
		],
		default: 'staging',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description: 'The POP API environment to use',
	},
	{
		displayName: 'Endpoint Path',
		name: 'path',
		type: 'string',
		default: 'sdi-via-pop/document-verify',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description: 'Relative path of the POP endpoint for document verification',
	},
	{
		displayName: 'Extra Headers (JSON)',
		name: 'headers',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['invoices'], operation: [OPERATION] } },
		description:
			'Optional additional headers as JSON object. Example: {"Content-Type":"application/xml"}.',
	},
];

// ── Internal helpers ─────────────────────────────────────────────────────────

/**
 * Tries to read the license_key from the upstream node's configured parameters
 * using n8n's workflow data proxy — the same mechanism used by the expression engine.
 *
 * Checks two strategies in order:
 * 1. Form mode: upstream node has a standalone `licenseKey` parameter.
 * 2. JSON mode: upstream node has a `jsonBody` parameter containing `license_key`.
 *
 * Returns undefined if detection fails.
 */
function detectLicenseKeyFromSource(
	execFns: IExecuteFunctions,
	itemIndex: number,
): string | undefined {
	try {
		const sourceData = execFns.getInputSourceData(0);
		const previousNode = sourceData?.previousNode;
		if (!previousNode) return undefined;

		const proxy = execFns.getWorkflowDataProxy(itemIndex);
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		const nodeProxy = (proxy.$node as any)[previousNode];
		if (!nodeProxy) return undefined;

		// Strategy 1 — form mode: licenseKey is a direct node parameter
		try {
			const lk = nodeProxy.parameter['licenseKey'] as unknown;
			if (typeof lk === 'string' && lk.trim()) return lk.trim();
		} catch {
			// parameter not present on this node — try next strategy
		}

		// Strategy 2 — JSON mode: license_key is embedded inside the jsonBody parameter
		try {
			const jsonBody = nodeProxy.parameter['jsonBody'] as unknown;
			if (typeof jsonBody === 'string' && jsonBody.trim()) {
				const parsed = JSON.parse(jsonBody) as Record<string, unknown>;
				if (typeof parsed.license_key === 'string' && parsed.license_key) {
					return parsed.license_key;
				}
			} else if (typeof jsonBody === 'object' && jsonBody !== null) {
				const lk = (jsonBody as Record<string, unknown>).license_key;
				if (typeof lk === 'string' && lk) return lk;
			}
		} catch {
			// parameter not present or jsonBody is not parseable JSON
		}
	} catch {
		// getInputSourceData or getWorkflowDataProxy unavailable
	}
	return undefined;
}

// ── Handler ──────────────────────────────────────────────────────────────────

/**
 * Operation handler — builds and sends the document-verify request.
 *
 * Takes the XML string from the incoming item (output of Create SdI Invoice),
 * base64-encodes it, and auto-detects the license_key from the upstream node.
 * skip_business_check is always true.
 */
export async function handler(
	this: IExecuteFunctions,
	params: {
		baseUrl?: string;
		path: string;
		headers?: Record<string, string>;
		_itemIndex?: number;
	},
): Promise<unknown> {
	const { baseUrl, path, headers } = params;
	const itemIndex = params._itemIndex ?? 0;

	const incomingJson = this.getInputData()[itemIndex].json;
	const licenseKey = detectLicenseKeyFromSource(this, itemIndex);

	let base64Xml: string;

	if (typeof incomingJson === 'string') {
		// Full workflow: the SDI node outputs the raw XML string directly.
		base64Xml = Buffer.from(incomingJson, 'utf-8').toString('base64');
	} else {
		// Standalone execution: extract integration.xml from the pasted object.
		const obj = incomingJson as Record<string, unknown>;
		const integration = obj.integration as Record<string, unknown> | undefined;
		const rawXml = integration?.xml;
		base64Xml = Buffer.from(typeof rawXml === 'string' ? rawXml : '', 'utf-8').toString('base64');
	}

	// When the license key was detected from the upstream node, send it as
	// X-API-Key (overriding the credential) so the verify call uses the same
	// key that produced the XML. license_key in the body is retained for
	// backwards compatibility with POP API deployments lacking auth-header support.
	const detectedHeaders = licenseKey
		? { ...(headers ?? {}), 'X-API-Key': licenseKey }
		: { ...(headers ?? {}) };

	const requestOptions: PopRequestOptions = {
		url: path,
		method: 'POST',
		json: true,
		headers: detectedHeaders,
		body: {
			license_key: licenseKey,
			skip_business_check: true,
			integration: { xml: base64Xml },
		},
	};

	return await popRequest.call(this, requestOptions, baseUrl);
}
